Comment out platform-dependent C_LONG typedefs
- After making C_LONG resolve at runtime at the previous
commit, C "long" type is no longer guaranteed to map to "OfLong" on
every platform (it maps to "OfInt" in Windows). It mapped to "OfLong"
because bindings were generated in Linux.
- So it is necessary to comment out the generated "OfLong" typedef
aliases in openpnp_capture.java, to fix this error:
"Incompatible types. Found: 'java.lang.foreign.ValueLayout', required:
'java.lang.foreign.ValueLayout.OfLong'" in those typedefs.